<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/dpl.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/bui.css">
    <title>User Management</title>
</head>
<body>
<div id="user-grid" style="margin:10px;"></div>

<!-- JS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.0.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/seed-min.js"></script>
<script type="text/javascript">
    var baseUrl="<?php echo $this->baseUrl(); ?>";
</script>
<script type="text/javascript">
    BUI.use(['bui/data','bui/grid','bui/overlay','bui/form'],function(Data,Grid,Overlay,Form){

    };
</script>
</body>
</html>