<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/dpl.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/bui.css">
    <title>User Management</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="control-group span6">
            <label class="control-label"></label>
            <div class="controls"><input/></div>
        </div>
    </div>
    <div class="row">
        <div class="span24">
            <button></button>
        </div>
    </div>
    <hr/>
    <div id="user-grid" style="margin:10px;"></div>
</div>
<!-- JS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.0.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/seed-min.js"></script>
<script type="text/javascript">
    var baseUrl="<?php echo $this->baseUrl(); ?>";
</script>
<script type="text/javascript">
    BUI.use(['bui/data','bui/grid','bui/overlay','bui/form'],function(Data,Grid,Overlay,Form){
        var addForm,editForm,addDialog,editDialog,store,columns,grid;
        store=new Data.Store({
            url:baseUrl+'/core/user/list',
            proxy:{
                method:'POST'
            }
        });
        columns=[{
            title:'ID',dataIndex:'id',width:100,elCls:'center'
        },{
            title:'Name',dataIndex:'uname',width:150,elCls:'center'
        },{
            title:'User Group',dataIndex:'usergroup',width:100,elCls:'center'
        },{
            title:'Status',dataIndex:'valid'
        },{
            title:'Handlers',elCls:'center',renderer:function(value,obj){
                return '<span class="grid-command edit-handler">edit</span>';
            }
        }];
        grid=new Grid.Grid({
            render:'#role-grid',
            width:510,
            columns:columns,
            loadMask:true,
            store:store,
            plugins:[Grid.Plugins.RowNumber],
            tbar:{
                items:[{
                    btnCls:'button button-small',
                    text:'New',
                    listeners:{
                        click:function(){
                            //
                        }
                    }
                }]
            },
            autoRender:true
        });
    };
</script>
</body>
</html>