<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/dpl.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/bui.css">
    <title>Role Management</title>
</head>
<body>
<div id="role-grid" style="margin:10px;"></div>
<div id="role-creator" class="hide">
    <form id="add-form" class="form-horizontal" action="<?php echo $this->baseUrl(); ?>/core/role/add" method="post">
        <div class="row">
            <div class="control-group span8">
                <label class="control-label"><?php echo $this->translator('role_code_label'); ?></label>
                <div class="controls">
                    <input type="text" id="a-role-code" name="role-code" class="input-small control-text" data-messages="{regexp:'Invalid Role Code'}" data-rules="{required:true,regexp:/^[A-Z]{2}$/}"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group span8">
                <label class="control-label"><?php echo $this->translator('role_name_label'); ?></label>
                <div class="controls">
                    <input type="text" id="a-role-name" name="role-name" class="input-normal control-text" data-rules="{required:true,maxlength:20}"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group span8">
                <label class="control-label"><?php echo $this->translator('role_status_label'); ?></label>
                <div class="controls">
                    <select id="a-role-status" name="role-status" class="input-normal">
                        <option value="Y">Valid</option>
                        <option value="N">Invalid</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group span15">
                <label class="control-label"><?php echo $this->translator('role_desc_label'); ?></label>
                <div class="controls control-row4">
                    <textarea id="a-role-desc" name="role-desc" class="input-large" data-rules="{maxlength:100}"></textarea>
                </div>
            </div>
        </div>
    </form>
</div>
<div id="role-editor" class="hide">
    <form id="edit-form" class="form-horizontal">
        <div class="row">
            <div class="control-group span8">
                <label class="control-label"><?php echo $this->translator('role_code_label'); ?></label>
                <div class="controls">
                    <input type="text" id="e-role-code" class="input-small control-text" disabled="disabled"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group span8">
                <label class="control-label"><?php echo $this->translator('role_name_label'); ?></label>
                <div class="controls">
                    <input type="text" id="e-role-name" class="input-normal control-text"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group span8">
                <label class="control-label"><?php echo $this->translator('role_status_label'); ?></label>
                <div class="controls">
                    <select id="e-role-status" class="input-normal">
                        <option value="Y">Valid</option>
                        <option value="N">Invalid</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group span15">
                <label class="control-label"><?php echo $this->translator('role_desc_label'); ?></label>
                <div class="controls control-row4">
                    <textarea id="e-role-desc" class="input-large"></textarea>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- JS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.0.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/seed-min.js"></script>
<script type="text/javascript">
    var baseUrl="<?php echo $this->baseUrl(); ?>";
</script>
<script type="text/javascript">
    BUI.use(['bui/data','bui/grid','bui/overlay','bui/form'],function(Data,Grid,Overlay,Form){
        var addForm,editForm,addDialog,editDialog,store,columns,grid;
        addForm=new Form.HForm({
            srcNode:'#add-form',
            submitType:'ajax',
            callback:function(data){
                if(data.success){
                    BUI.Message.Alert(data.info,'success');
                    $('#a-role-code').val('');
                    $('#a-role-name').val('');
                    $('#a-role-status').val('Y');
                    $('#a-role-desc').val('');
                    addDialog.close();
                    store.load();
                }else{
                    BUI.Message.Alert(data.info,'error');
                }
            }
        }).render();
        addDialog=new Overlay.Dialog({
            title:'New User Group',
            width:500,
            height:250,
            contentId:'role-creator',
            success:function(){
                addForm.submit();
            }
        });
        editForm=new Form.HForm({
            srcNode:'#edit-form'
        }).render();
        editDialog=new Overlay.Dialog({
            title:'Edit User Group',
            width:500,
            height:250,
            contentId:'role-editor',
            success:function(){
                alert('Hello');
            }
        });
        store=new Data.Store({
            url:baseUrl+'/core/role/list',
            proxy:{
                method:'POST'
            },
            autoLoad:true
        });
        columns=[{
            title:'Role Code',dataIndex:'rolecode',width:100,elCls:'center'
        },{
            title:'Role Name',dataIndex:'rolename',width:150,elCls:'center'
        },{
            title:'Current Status',dataIndex:'currentstatus',width:100,elCls:'center'
        },{
            title:'Handlers',elCls:'center',renderer:function(value,obj){
                return '<span class="grid-command edit-handler">edit</span>';
            }
        }];
        grid=new Grid.Grid({
            render:'#role-grid',
            width:510,
            columns:columns,
            loadMask:true,
            store:store,
            plugins:[Grid.Plugins.RowNumber],
            tbar:{
                items:[{
                    btnCls:'button button-small',
                    text:'New',
                    listeners:{
                        click:function(){
                            addDialog.show();
                        }
                    }
                }]
            },
            autoRender:true
        });
        grid.on('cellclick',function(ev){
            var record=ev.record;
            var field=ev.field;
            var target=$(ev.domTarget);
            if(target.hasClass('edit-handler')){
                $.post(baseUrl+'/core/role/detail',{code:record.rolecode},function(data){
                    if(data){
                        $('#e-role-code').val(data.rolecode);
                        $('#e-role-name').val(data.rolename);
                        $('#e-role-status').val(data.validflag);
                        $('#e-role-desc').val(data.description);
                        editDialog.show();
                    }
                },'json');
            }
        });
    });
</script>
</body>
</html>